service: hard

provider:
  name: aws
  runtime: python3.12
  stage: dev
  region: eu-west-2
  profile: serverless-user

functions:
  hard:
    handler: PUT.HANDLER.HERE

resources:
  Resources:
    hardResourcesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: hardResources
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: "User_ObjectType"
            KeyType: "HASH"
          - AttributeName: "Timestamp"
            KeyType: "RANGE"
