org: joecrockett
app: hard

service: hard

provider:
  name: aws
  runtime: python3.11
  stage: dev
  region: eu-west-2

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "logs:CreateLogStream"
            - "logs:CreateLogGroup"
          Resource: "arn:aws:logs:*:*:log-group:/aws/lambda/hard*:*"

        - Effect: Allow
          Action:
            - "logs:PutLogEvents"
          Resource: "arn:aws:logs:*:*:log-group:/aws/lambda/hard*:*:*"

        - Effect: Allow
          Action:
            - "dynamodb:Query"
            - "dynamodb:GetItem"
            - "dynamodb:Scan"
            - "dynamodb:PutItem"
            - "dynamodb:UpdateItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:BatchWriteItem"
          Resource: !GetAtt hardResourcesTable.Arn

functions:
  hard-api:
    handler: src.hard.app.main.handler
    layers:
      - Ref: PythonRequirementsLambdaLayer
    events:
      - http:
          path: /{endpoints+}
          method: ANY
          authorizer:
            name: CognitoAuth
            type: COGNITO_USER_POOLS
            arn: !GetAtt hardUserPool.Arn
    environment:
      DYNAMO_TABLE_NAME: hardResources
      DYNAMO_ITEM_INDEX_NAME: ItemSearch

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    name: ${self.provider.stage}-hard-api
    invalidateCaches: true
    useDownloadCache: false
    useStaticCache: false
    layer: true
    fileName: lambda-requirements.txt
    pipCmdExtraArgs:
      - --find-links .wheels/
      - --platform manylinux2014_x86_64
      - "--only-binary=:all:"

resources:
  Resources:
    hardResourcesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: hardResources
        BillingMode: PAY_PER_REQUEST

        AttributeDefinitions:
          - AttributeName: "User_ObjectType"
            AttributeType: S
          - AttributeName: "Timestamp"
            AttributeType: S
          - AttributeName: "object_id"
            AttributeType: S

        KeySchema:
          - AttributeName: "User_ObjectType"
            KeyType: "HASH"
          - AttributeName: "Timestamp"
            KeyType: "RANGE"

        GlobalSecondaryIndexes:
          - IndexName: ItemSearch

            KeySchema:
              - AttributeName: "object_id"
                KeyType: "HASH"

            Projection:
              ProjectionType: ALL

    hardUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: hardUserPool
        MfaConfiguration: OFF
        UsernameAttributes:
          - email
